name: Qwiet AI Scan

on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  NextGen-Static-Analysis:
    permissions:
      contents: read # Required for actions/checkout to fetch code
      security-events: write # Required for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # Needed in private repositories for github/codeql-action/upload-sarif
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository  # This is necessary to access your code
        uses: actions/checkout@v3
        
      - name: Run Qwiet AI Scan
        uses: sandy-qwietai/qwietai-actions@main
        env:
          SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
